import sys, json, torch
ckpt = torch.load(sys.argv[1], map_location='cpu', weights_only=False)
print('Keys:', sorted(ckpt.keys()))
print('Global step:', ckpt.get('global_step'))
print('Epoch:', ckpt.get('epoch'))
print('Optimizer saved:', 'optimizer_states' in ckpt)
print('LR scheduler saved:', 'lr_schedulers' in ckpt)
print()
print('=== fit_loop ===')
fit = ckpt.get('loops', {}).get('fit_loop', {})
print(json.dumps(fit, indent=2, default=str))
