#!/usr/bin/env bash
# Single source of truth for machine-specific paths.
#
# Do not edit this file. Put your overrides in env.local.sh (gitignored):
#
#   cat > env.local.sh <<'LOCAL'
#   export CVL_TOKENIZERS=/scratch/me/compvslike/tokenizers
#   export CVL_DATA=/scratch/me/compvslike/data
#   export CVL_SLURM_ACCOUNT=my_account
#   LOCAL
#
# Overrides are read first; everything below only fills in what is still unset.

CVL_ROOT="${CVL_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
[[ -f "${CVL_ROOT}/env.local.sh" ]] && source "${CVL_ROOT}/env.local.sh"
export CVL_ROOT

# Trained tokenisers (see tokenizer_training/).
export CVL_TOKENIZERS="${CVL_TOKENIZERS:-${CVL_ROOT}/tokenizers}"

# Raw + tokenised corpora (see data_prep/).
export CVL_DATA="${CVL_DATA:-${CVL_ROOT}/data}"
export CVL_RAW_EN="${CVL_RAW_EN:-${CVL_DATA}/fineweb-edu-raw}"
export CVL_RAW_MULTI="${CVL_RAW_MULTI:-${CVL_DATA}/multilingual-raw}"

# Training outputs and evaluation results.
export CVL_OUTPUTS="${CVL_OUTPUTS:-${CVL_ROOT}/outputs}"
export CVL_EVAL_OUT="${CVL_EVAL_OUT:-${CVL_ROOT}/eval_results}"
export CVL_LOGS="${CVL_LOGS:-${CVL_ROOT}/logs}"

# Hardware.
export CVL_NGPU="${CVL_NGPU:-4}"

# SLURM (used only by slurm/*.sbatch; ignored on bare metal).
export CVL_SLURM_ACCOUNT="${CVL_SLURM_ACCOUNT:-CHANGE_ME}"
export CVL_SLURM_PARTITION="${CVL_SLURM_PARTITION:-normal}"
export CVL_SLURM_TIME="${CVL_SLURM_TIME:-12:00:00}"
export CVL_CONTAINER_ENV="${CVL_CONTAINER_ENV:-}"   # e.g. enroot/pyxis env name
